import streamlit as st
import json
from db import get_session

session = get_session()

FOOTER = "All data is synthetic. GST information is treated as an indicative external data feed. Built with CoCo CLI: see PROMPTS.md in the repo."

# -- header band --
st.markdown(
    '<div style="background:#0B1F3A;padding:12px 24px;border-radius:6px;display:flex;'
    'justify-content:space-between;align-items:center;margin-bottom:16px;">'
    '<span style="color:white;font-size:1.4rem;font-weight:700;">LoanWatch</span>'
    '<span style="color:#ffffffcc;font-size:0.9rem;">Risk, Fraud and Regulatory Intelligence'
    ' Copilot &middot; Snowflake Cortex</span></div>',
    unsafe_allow_html=True,
)

st.subheader("\U0001f50e Signals")
st.caption(
    "Each row is one early-warning or credit signal generated by **ANOMALY_DETECTION** "
    "and rule-based checks on **dynamic tables** (LOAN_DPD_DAILY, ASSET_CLASS_DAILY, BORROWER_MONTHLY). "
    "Expand a row to see the evidence and the RBI clause."
)


def fmt_lakh(v):
    try:
        n = float(v)
        return f"\u20b9 {n / 1e5:,.1f} L"
    except (TypeError, ValueError):
        return str(v) if v is not None else ""


SEV_PILL = {
    "CRITICAL": ("background:#D64545;", "white"),
    "HIGH": ("background:#D64545;", "white"),
    "MEDIUM": ("background:#E8A33D;", "white"),
    "LOW": ("background:#888;", "white"),
}


def esc(text):
    import html as _html
    return _html.escape(str(text)) if text else ""


def sev_pill_html(sev):
    style, color = SEV_PILL.get(sev, ("background:#888;", "white"))
    return (f'<span style="{style}color:{color};padding:2px 10px;border-radius:12px;'
            f'font-size:0.8rem;font-weight:600;">{esc(sev)}</span>')


@st.cache_data(ttl=300)
def load_signals():
    return session.sql("""
        SELECT SIGNAL_ID, AS_OF_DATE, BORROWER_ID, BORROWER_NAME, EWS_CODE, EWS_NAME,
               CATEGORY, SEVERITY, METRIC_NAME, METRIC_VALUE, THRESHOLD,
               DETECTED_DATE, EVIDENCE, EVIDENCE_COUNT, EXPOSURE, ASSET_CLASS,
               CLAUSE_REF, STATUS
        FROM LOANWATCH.OUT.SIGNALS
        ORDER BY SEVERITY, BORROWER_NAME, EWS_CODE
    """).to_pandas()


df = load_signals()

# -- summary metrics --
c1, c2, c3, c4 = st.columns(4)
c1.metric("Total signals", len(df))
c2.metric("Open", int((df["STATUS"] == "OPEN").sum()))
c3.metric("Critical", int((df["SEVERITY"] == "CRITICAL").sum()))
c4.metric("Borrowers flagged", df["BORROWER_ID"].nunique())

# -- filters --
col1, col2, col3 = st.columns(3)
with col1:
    borrowers = ["All"] + sorted(df["BORROWER_NAME"].unique().tolist())
    sel_borrower = st.selectbox("Borrower", borrowers)
with col2:
    categories = ["All"] + sorted(df["CATEGORY"].unique().tolist())
    sel_category = st.selectbox("Category", categories)
with col3:
    severities = ["All"] + sorted(df["SEVERITY"].unique().tolist())
    sel_severity = st.selectbox("Severity", severities)

filtered = df.copy()
if sel_borrower != "All":
    filtered = filtered[filtered["BORROWER_NAME"] == sel_borrower]
if sel_category != "All":
    filtered = filtered[filtered["CATEGORY"] == sel_category]
if sel_severity != "All":
    filtered = filtered[filtered["SEVERITY"] == sel_severity]

# -- signal cards with severity pills and monospace clause refs --
for _, r in filtered.iterrows():
    pill = sev_pill_html(r["SEVERITY"])
    clause = esc(r["CLAUSE_REF"]) if r["CLAUSE_REF"] else ""
    clause_html = (f' &middot; <code style="font-family:monospace;background:#f0f0f0;'
                   f'padding:1px 6px;border-radius:3px;">{clause}</code>') if clause else ""
    exposure_str = esc(fmt_lakh(r["EXPOSURE"]))
    st.markdown(
        f'{pill} &nbsp; <b>{esc(r["EWS_CODE"])}</b> &mdash; {esc(r["BORROWER_NAME"])} &nbsp; '
        f'<span style="color:#666;">{esc(r["CATEGORY"])} &middot; {exposure_str}{clause_html}</span>',
        unsafe_allow_html=True,
    )

if filtered.empty:
    st.info("No signals match the current filters.")

# -- signal detail with evidence + clause expander --
st.subheader("\U0001f50e Signal detail")
signal_ids = filtered["SIGNAL_ID"].tolist()
if signal_ids:
    sel_signal = st.selectbox("Select a signal", signal_ids)
    row = filtered[filtered["SIGNAL_ID"] == sel_signal].iloc[0]
    sev = row["SEVERITY"]
    st.markdown(
        f'{sev_pill_html(sev)} &nbsp; <b>{esc(row["EWS_CODE"])}</b> &mdash; {esc(row["BORROWER_NAME"])}',
        unsafe_allow_html=True,
    )
    st.markdown(f"**Metric:** {row['METRIC_NAME']} = {row['METRIC_VALUE']} (threshold: {row['THRESHOLD']})")
    st.markdown(f"**Detected:** {row['DETECTED_DATE']}  |  **Evidence count:** {row['EVIDENCE_COUNT']}")
    st.markdown(f"**Exposure:** {fmt_lakh(row['EXPOSURE'])}  |  **Asset class:** {row['ASSET_CLASS']}")
    with st.expander("Evidence & RBI clause"):
        clause_ref = row["CLAUSE_REF"]
        if clause_ref:
            st.markdown(
                f'<b>Clause ref:</b> <code style="font-family:monospace;background:#f0f0f0;'
                f'padding:2px 8px;border-radius:3px;">{esc(clause_ref)}</code>',
                unsafe_allow_html=True,
            )
        evidence = row["EVIDENCE"]
        if isinstance(evidence, str):
            try:
                evidence = json.loads(evidence)
            except Exception:
                pass
        if evidence:
            st.json(evidence)
        else:
            st.info("No evidence detail available.")

st.divider()
st.caption(FOOTER)
