-- 50_judge_access.sql  –  Hackathon evaluator access
-- Passwords are NOT stored here; they were printed once at creation time.

--------------------------------------------------------------------
-- Role
--------------------------------------------------------------------
CREATE ROLE IF NOT EXISTS LW_JUDGE
  COMMENT = 'Hackathon evaluator – read-only access to LoanWatch';

--------------------------------------------------------------------
-- Grants to LW_JUDGE
--------------------------------------------------------------------
GRANT USAGE ON WAREHOUSE LW_APP_XS TO ROLE LW_JUDGE;

GRANT USAGE ON DATABASE LOANWATCH TO ROLE LW_JUDGE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE LOANWATCH TO ROLE LW_JUDGE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE LOANWATCH TO ROLE LW_JUDGE;

GRANT SELECT ON ALL TABLES IN DATABASE LOANWATCH TO ROLE LW_JUDGE;
GRANT SELECT ON ALL VIEWS IN DATABASE LOANWATCH TO ROLE LW_JUDGE;
GRANT SELECT ON FUTURE TABLES IN DATABASE LOANWATCH TO ROLE LW_JUDGE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE LOANWATCH TO ROLE LW_JUDGE;

GRANT USAGE ON STREAMLIT LOANWATCH.APP.LOANWATCH_UI TO ROLE LW_JUDGE;
GRANT USAGE ON CORTEX SEARCH SERVICE LOANWATCH.REF.REG_SEARCH TO ROLE LW_JUDGE;
GRANT USAGE ON AGENT LOANWATCH.APP.LOANWATCH_AGENT TO ROLE LW_JUDGE;
GRANT SELECT ON SEMANTIC VIEW LOANWATCH.APP.LOANWATCH_SV TO ROLE LW_JUDGE;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA LOANWATCH.OUT TO ROLE LW_JUDGE;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE LW_JUDGE;
GRANT ROLE LW_JUDGE TO ROLE ACCOUNTADMIN;

--------------------------------------------------------------------
-- Users  (passwords supplied out-of-band)
--------------------------------------------------------------------
CREATE USER IF NOT EXISTS EVALUATOR1
  EMAIL = 'evaluator@hack2skill.com'
  DEFAULT_ROLE = LW_JUDGE
  DEFAULT_WAREHOUSE = LW_APP_XS
  MUST_CHANGE_PASSWORD = FALSE
  COMMENT = 'Hackathon evaluator 1';

CREATE USER IF NOT EXISTS EVALUATOR2
  EMAIL = 'hack2skillevaluator@gmail.com'
  DEFAULT_ROLE = LW_JUDGE
  DEFAULT_WAREHOUSE = LW_APP_XS
  MUST_CHANGE_PASSWORD = FALSE
  COMMENT = 'Hackathon evaluator 2';

GRANT ROLE LW_JUDGE TO USER EVALUATOR1;
GRANT ROLE LW_JUDGE TO USER EVALUATOR2;
